"""add research paper tables

Revision ID: 975b8ebaed9e
Revises: f8fba9d0294f
Create Date: 2025-08-27 15:29:54.701501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975b8ebaed9e'
down_revision: Union[str, None] = 'f8fba9d0294f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
